version: '3.7'             
services:                                     
  rabbit: 
    build: 
      context: .
      dockerfile: Dockerfile.rabbitmq
    #    image: amazeeio/rabbitmq
    #command: sh -c "rabbitmq-plugins enable rabbitmq_management rabbitmq_delayed_message_exchange"
    volumes:                                               
      - rabbitmq:/var/lib/rabbitmq
    networks:
      - sge  
    ports:     
      - '5672:5672' # Queue server
      - '15672:15672' # Management portal
    environment:       
      # Available environment variables: https://www.rabbitmq.com/configure.html#supported-environment-variables
      # Its also possible to use Docker secrets(https://docs.docker.com/engine/swarm/secrets/) in a file with RABBITMQ_DEFAULT_USER_FILE and RABBITMQ_DEFAULT_PASS_FILE
      RABBITMQ_DEFAULT_USER: sge
      RABBITMQ_DEFAULT_PASS: sgetooR          
                          
#  be:                      
#    build: ../            
#    depends_on:       
#      - db             
#      - rabbit             
#    ports:           
#      - '3001:80' # Maps YOUR 3001 port to docker's 80 port
#    networks:            
#      - sge                 
#    env_file:                 
#      - ../.env
#    environment:
#      - PORT=80
#      - DB_DATABASE=sge
#      - DB_HOST=db
#      - DB_USER=root
#      - DB_PASSWORD=sgetooR
#      - QUEUEING_URI=amqp://sge:sgetooR@rabbit
#      - WAIT_HOSTS=db:3306
#      - WAIT_BEFORE_HOSTS=5
#      - WAIT_AFTER_HOSTS=5
#      - AUTH0_AUDIENCE
#      - AUTH0_CLIENT_ID
#      - AUTH0_CLIENT_SECRET
#      - CMS_PORTAL_ID
#      - CRM_SUBSCRIPTION_KEY
#      - FOREST_ENV_SECRET
#      - MENDEL_AUTHORIZATION
#      - TRADE_INSIGHTS_API_KEY

volumes:
  mysql:
  rabbitmq:

networks:
  sge:
